backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "moment" 
    label: "Moment" 
    folder: "pages/moments" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "moment"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Caption/Description", name: "caption", widget: "text"}
  - name: "work"
    label: "Work"
    folder: "pages/work" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "work"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Finish Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Partners", name: "partners", widget: "list"}
      - {label: "Description", name: "description", widget: "markdown"}
  - name: "experience"
    label: "Experience"
    folder: "pages/experience" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "experience"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date", name: "startdate", widget: "date"}
      - {label: "End Date", name: "enddate", widget: "date"}
      - {label: "Skills Earned", name: "skills", widget: "list"}
      - {label: "Description", name: "description", widget: "markdown"}

